import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { supabaseAdmin } from '../config/database';

export interface ReportData {
  title: string;
  subtitle?: string;
  period: string;
  generatedAt: string;
  generatedBy: string;
  sections: ReportSection[];
}

export interface ReportSection {
  title: string;
  type: 'overview' | 'chart' | 'table' | 'insights';
  data: any;
}

export interface BusinessReportData extends ReportData {
  overviewStats: Array<{
    label: string;
    value: string;
    change: string;
    trend: 'up' | 'down';
  }>;
  enrollmentTrend: Array<{
    month: string;
    enrollments: number;
    cost: number;
    roi: number;
  }>;
  departmentROI: Array<{
    department: string;
    investment: number;
    revenue: number;
    roi: number;
  }>;
  trainingCostBreakdown: Array<{
    name: string;
    value: number;
    color: string;
  }>;
  skillsDevelopment: Array<{
    skill: string;
    current: number;
    target: number;
  }>;
  productivityMetrics: Array<{
    month: string;
    before: number;
    after: number;
  }>;
  cohortComparison: Array<{
    metric: string;
    [key: string]: string | number;
  }>;
  keyInsights: Array<{
    title: string;
    description: string;
    impact: 'positive' | 'neutral' | 'negative';
    recommendation: string;
  }>;
}

export interface InstructorReportData extends ReportData {
  overviewStats: Array<{
    label: string;
    value: string;
    change: string;
    trend: 'up' | 'down';
  }>;
  revenueData: Array<{
    date: string;
    revenue: number;
    enrollments: number;
  }>;
  coursePerformance: Array<{
    name: string;
    students: number;
    revenue: number;
    rating: number;
    completion: number;
    engagement: number;
  }>;
  trafficSources: Array<{
    name: string;
    value: number;
    color: string;
  }>;
  studentLocations: Array<{
    country: string;
    students: number;
    percentage: number;
  }>;
  engagementData: Array<{
    day: string;
    avgTime: number;
    completion: number;
  }>;
  topLessons: Array<{
    title: string;
    views: number;
    avgTime: string;
    completion: number;
  }>;
}

export class ReportService {
  // Generate Business Analytics PDF Report
  static async generateBusinessReport(data: BusinessReportData): Promise<Buffer> {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    let yPosition = 20;

    // Helper function to add new page if needed
    const checkPageBreak = (requiredHeight: number) => {
      if (yPosition + requiredHeight > pageHeight - 20) {
        pdf.addPage();
        yPosition = 20;
      }
    };

    // Title Page
    pdf.setFontSize(24);
    pdf.setFont('helvetica', 'bold');
    pdf.text(data.title, pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 15;

    pdf.setFontSize(16);
    pdf.setFont('helvetica', 'normal');
    if (data.subtitle) {
      pdf.text(data.subtitle, pageWidth / 2, yPosition, { align: 'center' });
      yPosition += 10;
    }

    pdf.setFontSize(12);
    pdf.text(`Period: ${data.period}`, pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 8;
    pdf.text(`Generated: ${data.generatedAt}`, pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 8;
    pdf.text(`Generated by: ${data.generatedBy}`, pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 20;

    // Overview Stats
    checkPageBreak(40);
    pdf.setFontSize(18);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Executive Summary', 20, yPosition);
    yPosition += 15;

    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'normal');
    data.overviewStats.forEach((stat, index) => {
      checkPageBreak(20);
      pdf.text(`${stat.label}: ${stat.value}`, 25, yPosition);
      yPosition += 6;
      pdf.text(`  ${stat.change}`, 25, yPosition);
      yPosition += 8;
    });

    // Key Insights
    checkPageBreak(30);
    pdf.setFontSize(18);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Key Insights & Recommendations', 20, yPosition);
    yPosition += 15;

    data.keyInsights.forEach((insight, index) => {
      checkPageBreak(35);
      pdf.setFontSize(14);
      pdf.setFont('helvetica', 'bold');
      pdf.text(`${index + 1}. ${insight.title}`, 25, yPosition);
      yPosition += 8;

      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'normal');
      const descriptionLines = pdf.splitTextToSize(insight.description, pageWidth - 50);
      descriptionLines.forEach((line: string) => {
        pdf.text(line, 25, yPosition);
        yPosition += 5;
      });

      yPosition += 3;
      pdf.setFont('helvetica', 'italic');
      pdf.text(`Recommendation: ${insight.recommendation}`, 25, yPosition);
      yPosition += 10;
    });

    // Detailed Metrics
    checkPageBreak(30);
    pdf.setFontSize(18);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Detailed Metrics', 20, yPosition);
    yPosition += 15;

    // Enrollment Trends
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Enrollment & ROI Trends', 25, yPosition);
    yPosition += 10;

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.text('Month | Enrollments | Cost ($) | ROI (%)', 25, yPosition);
    yPosition += 6;
    pdf.text('------|------------|----------|---------', 25, yPosition);
    yPosition += 6;

    data.enrollmentTrend.forEach((trend) => {
      checkPageBreak(8);
      pdf.text(`${trend.month} | ${trend.enrollments} | ${trend.cost} | ${trend.roi}`, 25, yPosition);
      yPosition += 6;
    });

    // Department ROI
    checkPageBreak(30);
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text('ROI by Department', 25, yPosition);
    yPosition += 10;

    pdf.setFontSize(10);
    pdf.text('Department | Investment ($) | Revenue ($) | ROI (%)', 25, yPosition);
    yPosition += 6;
    pdf.text('-----------|----------------|-------------|---------', 25, yPosition);
    yPosition += 6;

    data.departmentROI.forEach((dept) => {
      checkPageBreak(8);
      pdf.text(`${dept.department} | ${dept.investment} | ${dept.revenue} | ${dept.roi}`, 25, yPosition);
      yPosition += 6;
    });

    // Footer
    const totalPages = pdf.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);
      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
      pdf.text('Confidential - For Internal Use Only', pageWidth / 2, pageHeight - 5, { align: 'center' });
    }

    return Buffer.from(pdf.output('arraybuffer'));
  }

  // Generate Instructor Analytics PDF Report
  static async generateInstructorReport(data: InstructorReportData): Promise<Buffer> {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    let yPosition = 20;

    // Helper function to add new page if needed
    const checkPageBreak = (requiredHeight: number) => {
      if (yPosition + requiredHeight > pageHeight - 20) {
        pdf.addPage();
        yPosition = 20;
      }
    };

    // Title Page
    pdf.setFontSize(24);
    pdf.setFont('helvetica', 'bold');
    pdf.text(data.title, pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 15;

    pdf.setFontSize(16);
    pdf.setFont('helvetica', 'normal');
    if (data.subtitle) {
      pdf.text(data.subtitle, pageWidth / 2, yPosition, { align: 'center' });
      yPosition += 10;
    }

    pdf.setFontSize(12);
    pdf.text(`Period: ${data.period}`, pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 8;
    pdf.text(`Generated: ${data.generatedAt}`, pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 8;
    pdf.text(`Generated by: ${data.generatedBy}`, pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 20;

    // Overview Stats
    checkPageBreak(40);
    pdf.setFontSize(18);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Performance Overview', 20, yPosition);
    yPosition += 15;

    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'normal');
    data.overviewStats.forEach((stat, index) => {
      checkPageBreak(20);
      pdf.text(`${stat.label}: ${stat.value}`, 25, yPosition);
      yPosition += 6;
      pdf.text(`  ${stat.change} vs last period`, 25, yPosition);
      yPosition += 8;
    });

    // Course Performance
    checkPageBreak(30);
    pdf.setFontSize(18);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Course Performance', 20, yPosition);
    yPosition += 15;

    data.coursePerformance.forEach((course, index) => {
      checkPageBreak(35);
      pdf.setFontSize(14);
      pdf.setFont('helvetica', 'bold');
      pdf.text(`${index + 1}. ${course.name}`, 25, yPosition);
      yPosition += 8;

      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`Students: ${course.students} | Revenue: $${course.revenue} | Rating: ${course.rating}/5`, 25, yPosition);
      yPosition += 6;
      pdf.text(`Completion: ${course.completion}% | Engagement: ${course.engagement}%`, 25, yPosition);
      yPosition += 10;
    });

    // Revenue Trends
    checkPageBreak(30);
    pdf.setFontSize(18);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Revenue & Enrollment Trends', 20, yPosition);
    yPosition += 15;

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.text('Date | Revenue ($) | Enrollments', 25, yPosition);
    yPosition += 6;
    pdf.text('-----|------------|-----------', 25, yPosition);
    yPosition += 6;

    data.revenueData.forEach((data) => {
      checkPageBreak(8);
      pdf.text(`${data.date} | ${data.revenue} | ${data.enrollments}`, 25, yPosition);
      yPosition += 6;
    });

    // Student Geography
    checkPageBreak(30);
    pdf.setFontSize(18);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Student Geography', 20, yPosition);
    yPosition += 15;

    data.studentLocations.forEach((location, index) => {
      checkPageBreak(15);
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`${index + 1}. ${location.country}: ${location.students} students (${location.percentage}%)`, 25, yPosition);
      yPosition += 8;
    });

    // Top Lessons
    checkPageBreak(30);
    pdf.setFontSize(18);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Top Performing Lessons', 20, yPosition);
    yPosition += 15;

    data.topLessons.forEach((lesson, index) => {
      checkPageBreak(20);
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'bold');
      pdf.text(`${index + 1}. ${lesson.title}`, 25, yPosition);
      yPosition += 6;

      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`Views: ${lesson.views} | Avg Time: ${lesson.avgTime} | Completion: ${lesson.completion}%`, 25, yPosition);
      yPosition += 8;
    });

    // Footer
    const totalPages = pdf.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);
      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
      pdf.text('Confidential - For Internal Use Only', pageWidth / 2, pageHeight - 5, { align: 'center' });
    }

    return Buffer.from(pdf.output('arraybuffer'));
  }

  // Generate CSV Report for Business Analytics
  static generateBusinessCSV(data: BusinessReportData): string {
    const headers = [
      'Report Title',
      'Period',
      'Generated At',
      'Generated By',
      'Metric',
      'Value',
      'Change',
      'Trend'
    ];

    const rows = data.overviewStats.map(stat => [
      data.title,
      data.period,
      data.generatedAt,
      data.generatedBy,
      stat.label,
      stat.value,
      stat.change,
      stat.trend
    ]);

    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
    ].join('\n');

    return csvContent;
  }

  // Generate CSV Report for Instructor Analytics
  static generateInstructorCSV(data: InstructorReportData): string {
    const headers = [
      'Report Title',
      'Period',
      'Generated At',
      'Generated By',
      'Metric',
      'Value',
      'Change',
      'Trend'
    ];

    const rows = data.overviewStats.map(stat => [
      data.title,
      data.period,
      data.generatedAt,
      data.generatedBy,
      stat.label,
      stat.value,
      stat.change,
      stat.trend
    ]);

    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
    ].join('\n');

    return csvContent;
  }

  // Save report to database (optional - for audit trail)
  static async saveReportRecord(userId: string, reportType: string, fileName: string, fileSize: number): Promise<void> {
    try {
      await supabaseAdmin
        .from('report_exports')
        .insert({
          user_id: userId,
          report_type: reportType,
          file_name: fileName,
          file_size: fileSize,
          created_at: new Date().toISOString()
        });
    } catch (error) {
      console.error('Error saving report record:', error);
      // Don't throw error for non-critical operation
    }
  }
}
